language: php

php:
  - '5.6'
  - '7.0'
  - hhvm

sudo: false


services:
  - mysql

before_script:
  - cp .env.travis .env
  - mysql -e 'create database homestead_test;'
  - php artisan migrate -vvv
  - composer self-update
  - git config --global user.email $EMAIL_ADDRESS
  - git config --global user.name $USER_NAME
  - git config --global push.default matching

cache:
  directories:
    - ./vendor


notifications:
  email:
    recipients:
      - zqh0513@gmail.com
    on_success: always
    on_failure: always

script: vendor/bin/phpunit -c phpunit.xml

deploy:
  provider: openshift
  user: $OPENSSHITF_USERNAME
  password: $OPENSHITF_PASSWORD
  domain: $OPENSSHITF_DOMAIN
  app: $APP_NAME
  deployment_branch: master
  on:
    repo: zqhong/Lizard
    all_branches: true