language: php

php:
  - 5.6
  - '7.0'
  - hhvm
  - nightly

sudo: false

install:
  - composer --prefer-source install

cache:
  directories:
    - ./vendor

notifications:
  email:
    recipients:
      - zqh0513@gmail.com
    on_success: always
    on_failure: always

script: vendor/bin/phpunit -c phpunit.xml
